name: CI/CD Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  versionamento:
    runs-on: ubuntu-latest
    name: Versionamento

    permissions:
      contents: write

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix Git Permissions and Fetch tags
        run: |
          git config --global --add safe.directory '*'
          git fetch --tags --force

      - name: Run Git Version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          release-branch: master
          prefix: v

      - name: Tag do Repositório
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag ${{ steps.version.outputs.version }}
          git push origin --tags

  build:
    runs-on: ubuntu-latest
    name: Build Project
    needs: versionamento

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.0.x'
          cache: true
          cache-dependency-path: |
            Poc_01.sln

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Test project
        run: |
          dotnet test \
            --no-build \
            --configuration Release \
            --verbosity normal \
            --logger trx \
            --results-directory "TestResults"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults

      - name: Publish Project
        run: |
          dotnet publish Poc_01.csproj \
            -c Release \
            -o ./publish \
            --no-build

      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ./publish

  backend-lint:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Backend Lint

    if: github.ref != 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: "master"
          VALIDATE_ALL_CODEBASE: "false"
          VALIDATE_YAML: "true"
          VALIDATE_CSHARP: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-security-check:
    name: Code Security Check
    needs: versionamento
    runs-on: ubuntu-latest

    if: github.ref != 'refs/heads/master'

    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      matrix:
        include:
          - name: Backend
            language: csharp
            build-mode: autobuild

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL - ${{ matrix.name }}
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Analyze code - ${{ matrix.name }}
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

  build-docker-image:
    name: Packing and Publish
    needs:
      - versionamento
      - build

    runs-on: ubuntu-latest

    env:
      version: ${{ needs.versionamento.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Publish Artifact
        uses: actions/download-artifact@v4
        with:
          name: web
          path: ./publish

      - name: Docker Build Image
        run: |
          docker build \
            -t ${{ vars.DOCKERHUB_REPOSITORY }}:${{ env.version }} .

      - name: Tag Docker as Latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag \
            ${{ vars.DOCKERHUB_REPOSITORY }}:${{ env.version }} \
            ${{ vars.DOCKERHUB_REPOSITORY }}:latest

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Push
        run: |
          docker push --all-tags ${{ vars.DOCKERHUB_REPOSITORY }}