name: Build Project

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  versionamento:
    runs-on: ubuntu-latest
    name: Versionamento

    permissions:
      contents: write

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix Git Permissions and Fetch tags
        run: |
          git config --global --add safe.directory '*'
          git fetch --tags --force

      - name: Run Git Version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          release-branch: master
          prefix: v

      - name: Tag do Repositório
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag ${{ steps.version.outputs.version }}
          git push origin --tags

      - name: Create file versão
        if: github.ref == 'refs/